---
- hosts: all
  become: yes

  vars:
          node_apps_location: /usr/local/opt/node
  tasks:
  # Setup and install nodejs on the server
    - name: Install EPEL repo
      yum: name=epel-release state=present

    - name: Import Remi GPG Key
      rpm_key: 
        key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
        state: present

    - name: Install Remi repo
      yum:
          name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
          state: present

    - name: Ensure firewalld is stopped
      service: name=firewalld state=stopped

    - name: Install Node.js and npm
      yum: name=npm state=present enablerepo=epel

    - name: Install forever(to run app)
      npm: name=forever global=yes state=present

# Copy the nodeJS application to the server
    # Check if file directory exists; node_apps_location was defined in vars
    - name: Ensure Node.js app folder exists
      file: "path={{ node_apps_location }} state=directory"
    # Copy the app folder to node_apps_location
    - name: Copy example Node.js app to server
      copy: "src=app dest={{node_apps_location }}"

    # Tells npm to build the project and ensure dependencies are present
    - name: Install app dependencies defined in package.json
      npm: path={{node_apps_location}}/app

    # Create a new variable called forever_list
    - name: Check currently running nodeJS apps
      command: forever list
      register: forever_list
      changed_when: false

    # Start the app using forever; the when option ensures we only start the app if an instance is not already running
    - name: Start NodeJS app
      command: "forever start {{ node_apps_location }}/app/app.js"
      when: "forever_list.stdout.find(node_apps_location+\
    '/app/app.js') == -1"
